@echo off
echo Starting Social Live Backend with Hot Reload...
cd social-live-mvp
echo Installing dependencies...
call npm install
echo Starting development server with auto-restart...
call npm run start:dev