@echo off
echo Starting backend server with hot reload...
cd social-live-mvp
echo Installing dependencies if needed...
call npm install
echo Starting server with auto-restart...
call npm run dev:minimal