class MockVideoData {
  static List<Map<String, dynamic>> getMockVideos() {
    return [
      {
        'id': '1',
        'content': 'Amazing sunset timelapse! 🌅 #nature #sunset',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        'type': 'VIDEO',
        'likesCount': 1234,
        'commentsCount': 89,
        'isLiked': false,
        'user': {
          'id': '1',
          'username': 'naturelover',
          'avatar': 'https://i.pravatar.cc/150?img=1',
        },
        'createdAt': '2024-01-01T12:00:00Z',
      },
      {
        'id': '2',
        'content': 'Dancing in the rain! 💃 #dance #fun',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        'type': 'VIDEO',
        'likesCount': 567,
        'commentsCount': 23,
        'isLiked': true,
        'user': {
          'id': '2',
          'username': 'dancer_girl',
          'avatar': 'https://i.pravatar.cc/150?img=2',
        },
        'createdAt': '2024-01-01T11:00:00Z',
      },
      {
        'id': '3',
        'content': 'Cooking tutorial: Perfect pasta! 🍝 #cooking #food',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        'type': 'VIDEO',
        'likesCount': 890,
        'commentsCount': 45,
        'isLiked': false,
        'user': {
          'id': '3',
          'username': 'chef_master',
          'avatar': 'https://i.pravatar.cc/150?img=3',
        },
        'createdAt': '2024-01-01T10:00:00Z',
      },
      {
        'id': '4',
        'content': 'Street art in the city 🎨 #art #street',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        'type': 'VIDEO',
        'likesCount': 2345,
        'commentsCount': 156,
        'isLiked': false,
        'user': {
          'id': '4',
          'username': 'street_artist',
          'avatar': 'https://i.pravatar.cc/150?img=4',
        },
        'createdAt': '2024-01-01T09:00:00Z',
      },
      {
        'id': '5',
        'content': 'Morning workout routine 💪 #fitness #health',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        'type': 'VIDEO',
        'likesCount': 678,
        'commentsCount': 34,
        'isLiked': true,
        'user': {
          'id': '5',
          'username': 'fitness_guru',
          'avatar': 'https://i.pravatar.cc/150?img=5',
        },
        'createdAt': '2024-01-01T08:00:00Z',
      },
      {
        'id': '6',
        'content': 'Beautiful landscape photography 📸 #photography',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
        'type': 'VIDEO',
        'likesCount': 1567,
        'commentsCount': 78,
        'isLiked': false,
        'user': {
          'id': '6',
          'username': 'photographer',
          'avatar': 'https://i.pravatar.cc/150?img=6',
        },
        'createdAt': '2024-01-01T07:00:00Z',
      },
      {
        'id': '7',
        'content': 'Travel vlog from Paris 🇫🇷 #travel #paris',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        'type': 'VIDEO',
        'likesCount': 3421,
        'commentsCount': 234,
        'isLiked': true,
        'user': {
          'id': '7',
          'username': 'traveler',
          'avatar': 'https://i.pravatar.cc/150?img=7',
        },
        'createdAt': '2024-01-01T06:00:00Z',
      },
      {
        'id': '8',
        'content': 'DIY home decoration ideas 🏠 #diy #home',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
        'type': 'VIDEO',
        'likesCount': 987,
        'commentsCount': 67,
        'isLiked': false,
        'user': {
          'id': '8',
          'username': 'diy_expert',
          'avatar': 'https://i.pravatar.cc/150?img=8',
        },
        'createdAt': '2024-01-01T05:00:00Z',
      },
      {
        'id': '9',
        'content': 'Gaming highlights! 🎮 #gaming #esports',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
        'type': 'VIDEO',
        'likesCount': 4521,
        'commentsCount': 312,
        'isLiked': false,
        'user': {
          'id': '9',
          'username': 'pro_gamer',
          'avatar': 'https://i.pravatar.cc/150?img=9',
        },
        'createdAt': '2024-01-01T04:00:00Z',
      },
      {
        'id': '10',
        'content': 'Fashion trends 2024 👗 #fashion #style',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        'type': 'VIDEO',
        'likesCount': 2876,
        'commentsCount': 189,
        'isLiked': true,
        'user': {
          'id': '10',
          'username': 'fashionista',
          'avatar': 'https://i.pravatar.cc/150?img=10',
        },
        'createdAt': '2024-01-01T03:00:00Z',
      },
      {
        'id': '11',
        'content': 'Tech review: Latest gadgets 📱 #tech #review',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
        'type': 'VIDEO',
        'likesCount': 1987,
        'commentsCount': 145,
        'isLiked': false,
        'user': {
          'id': '11',
          'username': 'tech_reviewer',
          'avatar': 'https://i.pravatar.cc/150?img=11',
        },
        'createdAt': '2024-01-01T02:00:00Z',
      },
      {
        'id': '12',
        'content': 'Pet compilation 🐶🐱 #pets #cute',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
        'type': 'VIDEO',
        'likesCount': 5432,
        'commentsCount': 421,
        'isLiked': true,
        'user': {
          'id': '12',
          'username': 'pet_lover',
          'avatar': 'https://i.pravatar.cc/150?img=12',
        },
        'createdAt': '2024-01-01T01:00:00Z',
      },
      {
        'id': '13',
        'content': 'Music cover performance 🎵 #music #cover',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
        'type': 'VIDEO',
        'likesCount': 3210,
        'commentsCount': 267,
        'isLiked': false,
        'user': {
          'id': '13',
          'username': 'musician',
          'avatar': 'https://i.pravatar.cc/150?img=13',
        },
        'createdAt': '2024-01-01T00:00:00Z',
      },
      {
        'id': '14',
        'content': 'Comedy sketch 😂 #comedy #funny',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        'type': 'VIDEO',
        'likesCount': 6789,
        'commentsCount': 534,
        'isLiked': true,
        'user': {
          'id': '14',
          'username': 'comedian',
          'avatar': 'https://i.pravatar.cc/150?img=14',
        },
        'createdAt': '2023-12-31T23:00:00Z',
      },
      {
        'id': '15',
        'content': 'Motivational speech 💯 #motivation #inspiration',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        'type': 'VIDEO',
        'likesCount': 4123,
        'commentsCount': 298,
        'isLiked': false,
        'user': {
          'id': '15',
          'username': 'motivator',
          'avatar': 'https://i.pravatar.cc/150?img=15',
        },
        'createdAt': '2023-12-31T22:00:00Z',
      },
    ];
  }
}
