class MockVideoData {
  static List<Map<String, dynamic>> getMockVideos() {
    return [
      {
        'id': '1',
        'content': 'Amazing sunset timelapse! 🌅 #nature #sunset',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        'type': 'VIDEO',
        'likesCount': 1234,
        'commentsCount': 89,
        'isLiked': false,
        'user': {
          'id': '1',
          'username': 'naturelover',
          'avatar': 'https://i.pravatar.cc/150?img=1',
        },
        'createdAt': '2024-01-01T12:00:00Z',
      },
      {
        'id': '2',
        'content': 'Dancing in the rain! 💃 #dance #fun',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        'type': 'VIDEO',
        'likesCount': 567,
        'commentsCount': 23,
        'isLiked': true,
        'user': {
          'id': '2',
          'username': 'dancer_girl',
          'avatar': 'https://i.pravatar.cc/150?img=2',
        },
        'createdAt': '2024-01-01T11:00:00Z',
      },
      {
        'id': '3',
        'content': 'Cooking tutorial: Perfect pasta! 🍝 #cooking #food',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        'type': 'VIDEO',
        'likesCount': 890,
        'commentsCount': 45,
        'isLiked': false,
        'user': {
          'id': '3',
          'username': 'chef_master',
          'avatar': 'https://i.pravatar.cc/150?img=3',
        },
        'createdAt': '2024-01-01T10:00:00Z',
      },
      {
        'id': '4',
        'content': 'Street art in the city 🎨 #art #street',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        'type': 'VIDEO',
        'likesCount': 2345,
        'commentsCount': 156,
        'isLiked': false,
        'user': {
          'id': '4',
          'username': 'street_artist',
          'avatar': 'https://i.pravatar.cc/150?img=4',
        },
        'createdAt': '2024-01-01T09:00:00Z',
      },
      {
        'id': '5',
        'content': 'Morning workout routine 💪 #fitness #health',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        'type': 'VIDEO',
        'likesCount': 678,
        'commentsCount': 34,
        'isLiked': true,
        'user': {
          'id': '5',
          'username': 'fitness_guru',
          'avatar': 'https://i.pravatar.cc/150?img=5',
        },
        'createdAt': '2024-01-01T08:00:00Z',
      },
      {
        'id': '6',
        'content': 'Beautiful landscape photography 📸 #photography',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        'type': 'VIDEO',
        'likesCount': 1567,
        'commentsCount': 78,
        'isLiked': false,
        'user': {
          'id': '6',
          'username': 'photographer',
          'avatar': 'https://i.pravatar.cc/150?img=6',
        },
        'createdAt': '2024-01-01T07:00:00Z',
      },
      {
        'id': '7',
        'content': 'Travel vlog from Paris 🇫🇷 #travel #paris',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        'type': 'VIDEO',
        'likesCount': 3421,
        'commentsCount': 234,
        'isLiked': true,
        'user': {
          'id': '7',
          'username': 'traveler',
          'avatar': 'https://i.pravatar.cc/150?img=7',
        },
        'createdAt': '2024-01-01T06:00:00Z',
      },
      {
        'id': '8',
        'content': 'DIY home decoration ideas 🏠 #diy #home',
        'mediaUrl': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        'type': 'VIDEO',
        'likesCount': 987,
        'commentsCount': 67,
        'isLiked': false,
        'user': {
          'id': '8',
          'username': 'diy_expert',
          'avatar': 'https://i.pravatar.cc/150?img=8',
        },
        'createdAt': '2024-01-01T05:00:00Z',
      },
    ];
  }
}
